## Importing Libraries

In [3]:
import pandas as pd

import sys
sys.path.append("../")  
from src.data_collection import get_movie_details, get_movie_keywords
# in order to use these modules, I'm using an API_KEY. If you try to rerun the code, it'll fail if you don't add your API_KEY

## Loading Datasets

We have several datasets, we'll load all of them here. We'll see what each one of them have,

### MovieLens

MovieLens will be our base. There are two reasons for this:
- It has the links dataset which will be the core of our future database in SQL
- They are the cleanest and clearest datasets
- It only has movies. IMBD includes some TVshows and other stuff, not only movies.

It has almost 90.000 records which will make also all our datasets more manageable

In [16]:
links = pd.read_csv("../data/raw/movielens/links.csv")
links.head()

   movieId  imdbId   tmdbId
0        1  114709    862.0
1        2  113497   8844.0
2        3  113228  15602.0
3        4  114885  31357.0
4        5  113041  11862.0

In [17]:
links.shape

(86537, 3)

In [20]:
movies = pd.read_csv("../data/raw/movielens/movies.csv")
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [21]:
movies.shape

(86537, 3)

In [22]:
ratings = pd.read_csv("../data/raw/movielens/ratings.csv")
ratings.head()

   userId  movieId  rating   timestamp
0       1        1     4.0  1225734739
1       1      110     4.0  1225865086
2       1      158     4.0  1225733503
3       1      260     4.5  1225735204
4       1      356     5.0  1225735119

In [23]:
ratings.shape

(33832162, 4)

### IMDB

These datasets have a lot of information and require a lot of cleaning and decision making on several areas. However, we'll do that on the cleaning part. We'll just load them here.

In [6]:
name_basics = pd.read_csv("../data/raw/imbd/name.basics.tsv", sep='\t')
name_basics.head()

,nconst,primaryName,birthYear,deathYear,primaryProfession,knownForTitles
0,nm0000001,Fred Astaire,1899,1987,"actor,miscellaneous,producer","tt0072308,tt0050419,tt0027125,tt0025164"
1,nm0000002,Lauren Bacall,1924,2014,"actress,miscellaneous,soundtrack","tt0037382,tt0075213,tt0038355,tt0045891"
2,nm0000003,Brigitte Bardot,1934,2025,"actress,music_department,producer","tt0057345,tt0049189,tt0056404,tt0054452"
3,nm0000004,John Belushi,1949,1982,"actor,writer,music_department","tt0072562,tt0077975,tt0080455,tt0078723"
4,nm0000005,Ingmar Bergman,1918,2007,"writer,director,actor","tt0050986,tt0069467,tt0050976,tt0083922"

In [7]:
name_basics.shape

(15336275, 6)

In [8]:
title_basics = pd.read_csv("../data/raw/imbd/title.basics.tsv", sep='\t')
title_basics.head()

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,tt0000001,short,Carmencita,Carmencita,0,1894,\N,1,"Documentary,Short"
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0,1892,\N,5,"Animation,Short"
2,tt0000003,short,Poor Pierrot,Pauvre Pierrot,0,1892,\N,5,"Animation,Comedy,Romance"
3,tt0000004,short,Un bon bock,Un bon bock,0,1892,\N,12,"Animation,Short"
4,tt0000005,short,Blacksmith Scene,Blacksmith Scene,0,1893,\N,1,Short

In [9]:
title_basics.shape

(12508399, 9)

In [10]:
title_crew = pd.read_csv("../data/raw/imbd/title.crew.tsv", sep='\t')
title_crew.head()

      tconst  directors    writers
0  tt0000001  nm0005690         \N
1  tt0000002  nm0721526         \N
2  tt0000003  nm0721526  nm0721526
3  tt0000004  nm0721526         \N
4  tt0000005  nm0005690         \N

In [11]:
title_crew.shape

(12508399, 3)

In [12]:
title_principals = pd.read_csv("../data/raw/imbd/title.principals.tsv", sep='\t')
title_principals.head()

,tconst,ordering,nconst,category,job,characters
0,tt0000001,1,nm1588970,self,\N,"[""Self""]"
1,tt0000001,2,nm0005690,director,\N,\N
2,tt0000001,3,nm0005690,producer,producer,\N
3,tt0000001,4,nm0374658,cinematographer,director of photography,\N
4,tt0000002,1,nm0721526,director,\N,\N

In [13]:
title_principals.shape

(99496955, 6)

In [14]:
title_ratings = pd.read_csv("../data/raw/imbd/title.ratings.tsv", sep='\t')
title_ratings.head()

      tconst  averageRating  numVotes
0  tt0000001            5.7      2216
1  tt0000002            5.5       318
2  tt0000003            6.4      2334
3  tt0000004            5.1       199
4  tt0000005            6.2      3052

In [15]:
title_ratings.shape

(1670967, 3)

### Kaggle

The original idea was to use the Bechdel API, but it had been discontinued. 

So, even though, this is a clear limitation it is still a good option in order to include a gender perspective.

In [24]:
bechdel = pd.read_csv("../data/external/bechdel_detailed.csv")
bechdel.head()

,Unnamed: 0,title,year,rating,dubious,imdbid,id,submitterid,date,visible
0,0,Passage de Venus,1874.0,0.0,0.0,3155794.0,9602.0,18880.0,2021-04-02 20:58:09,1.0
1,1,La Rosace Magique,1877.0,0.0,0.0,14495706.0,9804.0,19145.0,2021-05-11 00:11:22,1.0
2,2,Sallie Gardner at a Gallop,1878.0,0.0,0.0,2221420.0,9603.0,18882.0,2021-04-03 02:25:27,1.0
3,3,Le singe musicien,1878.0,0.0,0.0,12592084.0,9806.0,19151.0,2021-05-11 23:38:54,1.0
4,4,Athlete Swinging a Pick,1881.0,0.0,0.0,7816420.0,9816.0,19162.0,2021-05-13 01:32:14,1.0

In [27]:
bechdel.shape

(9373, 10)

### TMDB API

The Movie Database (TMDB) API will help us get information from the budget and revenue to film's posters for our Streamlit app.

In [ ]:
# Test with The Godfather (tmdb_id = 238)
movie = get_movie_details(238)
keywords = get_movie_keywords(238)

print(f"Title: {movie['title']}")
print(f"Budget: ${movie['budget']:,}")
print(f"Revenue: ${movie['revenue']:,}")
print(f"Keywords: {[k['name'] for k in keywords['keywords'][:10]]}")

Title: The Godfather
Budget: $6,000,000
Revenue: $245,066,411
Keywords: ['based on novel or book', 'loss of loved one', 'love at first sight', 'italy', 'gangster', 'symbolism', 'patriarch', 'europe', 'organized crime', 'mafia']

## Cleaning the Datasets

In [18]:
links['imdb_id'] = 'tt' + links['imdbId'].astype(str).str.zfill(7)
links.head()

   movieId  imdbId   tmdbId    imdb_id
0        1  114709    862.0  tt0114709
1        2  113497   8844.0  tt0113497
2        3  113228  15602.0  tt0113228
3        4  114885  31357.0  tt0114885
4        5  113041  11862.0  tt0113041

In [19]:
title_basics[title_basics["tconst"].isin(links["imdb_id"])]["titleType"].value_counts()

titleType
movie           70580
tvMovie          5893
short            5234
video            2141
tvSpecial         882
tvEpisode         753
tvMiniSeries      530
tvShort           166
tvSeries          137
videoGame           2
Name: count, dtype: int64