In [1]:
import pandas as pd

In [4]:
name_basics = pd.read_csv("./name.basics.tsv", sep='\t', header=0)
name_basics.head()

,nconst,primaryName,birthYear,deathYear,primaryProfession,knownForTitles
0,nm0000001,Fred Astaire,1899,1987,"actor,miscellaneous,producer","tt0072308,tt0050419,tt0027125,tt0025164"
1,nm0000002,Lauren Bacall,1924,2014,"actress,miscellaneous,soundtrack","tt0037382,tt0075213,tt0038355,tt0045891"
2,nm0000003,Brigitte Bardot,1934,2025,"actress,music_department,producer","tt0057345,tt0049189,tt0056404,tt0054452"
3,nm0000004,John Belushi,1949,1982,"actor,writer,music_department","tt0072562,tt0077975,tt0080455,tt0078723"
4,nm0000005,Ingmar Bergman,1918,2007,"writer,director,actor","tt0050986,tt0069467,tt0050976,tt0083922"

In [5]:
name_basics.shape

(15336275, 6)

In [11]:
titles_akas = pd.read_csv("./title.akas.tsv", sep='\t', header=0)
titles_akas.head()

,titleId,ordering,title,region,language,types,attributes,isOriginalTitle
0,tt0000001,1,Carmencita,\N,\N,original,\N,1
1,tt0000001,2,Carmencita,DE,\N,\N,literal title,0
2,tt0000001,3,Carmencita,US,\N,imdbDisplay,\N,0
3,tt0000001,4,Carmencita - spanyol tánc,HU,\N,imdbDisplay,\N,0
4,tt0000001,5,Καρμενσίτα,GR,\N,imdbDisplay,\N,0

In [12]:
titles_akas.shape

(57124433, 8)

In [13]:
title_basics = pd.read_csv("./title.basics.tsv", sep='\t', header=0)
title_basics.head()

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,tt0000001,short,Carmencita,Carmencita,0,1894,\N,1,"Documentary,Short"
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0,1892,\N,5,"Animation,Short"
2,tt0000003,short,Poor Pierrot,Pauvre Pierrot,0,1892,\N,5,"Animation,Comedy,Romance"
3,tt0000004,short,Un bon bock,Un bon bock,0,1892,\N,12,"Animation,Short"
4,tt0000005,short,Blacksmith Scene,Blacksmith Scene,0,1893,\N,1,Short

In [14]:
title_basics.shape

(12508399, 9)

In [16]:
title_crew = pd.read_csv("./title.crew.tsv", sep='\t', header=0)
title_crew.head()

      tconst  directors    writers
0  tt0000001  nm0005690         \N
1  tt0000002  nm0721526         \N
2  tt0000003  nm0721526  nm0721526
3  tt0000004  nm0721526         \N
4  tt0000005  nm0005690         \N

In [17]:
title_crew.shape

(12508399, 3)

In [18]:
title_episode = pd.read_csv("./title.episode.tsv", sep='\t', header=0)
title_episode.head()

      tconst parentTconst seasonNumber episodeNumber
0  tt0031458   tt32857063           \N            \N
1  tt0041951    tt0041038            1             9
2  tt0042816    tt0989125            1            17
3  tt0042889    tt0989125           \N            \N
4  tt0043426    tt0040051            3            42

In [19]:
title_episode.shape

(9661392, 4)

In [20]:
title_principals = pd.read_csv("./title.principals.tsv", sep='\t', header=0)
title_principals.head()

,tconst,ordering,nconst,category,job,characters
0,tt0000001,1,nm1588970,self,\N,"[""Self""]"
1,tt0000001,2,nm0005690,director,\N,\N
2,tt0000001,3,nm0005690,producer,producer,\N
3,tt0000001,4,nm0374658,cinematographer,director of photography,\N
4,tt0000002,1,nm0721526,director,\N,\N

In [21]:
title_principals.shape

(99496955, 6)

In [22]:
title_ratings = pd.read_csv("./title.ratings.tsv", sep='\t', header=0)
title_ratings.head()

      tconst  averageRating  numVotes
0  tt0000001            5.7      2216
1  tt0000002            5.5       318
2  tt0000003            6.4      2334
3  tt0000004            5.1       199
4  tt0000005            6.2      3052

In [23]:
title_ratings.shape

(1670967, 3)

In [27]:
import requests
api_key = "fde98c496a9cabc93a2c764a952509da"
url = "https://api.themoviedb.org/3/movie/popular"

params = {
    "api_key": api_key,
    "language": "en-US",
    "page": 1
}

response = requests.get(url, params=params)
data = response.json()
print(data)

{'page': 1, 'results': [{'adult': False, 'backdrop_path': '/cccXiN28CPjcMVhji5LnogF4Njp.jpg', 'genre_ids': [28, 18, 80], 'id': 1439930, 'title': 'The Punisher: One Last Kill', 'original_language': 'en', 'original_title': 'The Punisher: One Last Kill', 'overview': 'As Frank Castle searches for meaning beyond revenge, an unexpected force pulls him back into the fight.', 'popularity': 716.6387, 'poster_path': '/qQclTgLMDvGBuUBFGHRipxkEwWR.jpg', 'release_date': '2026-05-12', 'softcore': False, 'video': False, 'vote_average': 8.567, 'vote_count': 849}, {'adult': False, 'backdrop_path': '/2I1OFQJ0L9T0dpU6FobKFWV2PxX.jpg', 'genre_ids': [878, 12], 'id': 687163, 'title': 'Project Hail Mary', 'original_language': 'en', 'original_title': 'Project Hail Mary', 'overview': 'Science teacher Ryland Grace wakes up on a spaceship light years from home with no recollection of who he is or how he got there. As his memory returns, he begins to uncover his mission: solve the riddle of the mysterious substance causing the sun to die out. He must call on his scientific knowledge and unorthodox ideas to save everything on Earth from extinction.', 'popularity': 479.091, 'poster_path': '/yihdXomYb5kTeSivtFndMy5iDmf.jpg', 'release_date': '2026-03-15', 'softcore': False, 'video': False, 'vote_average': 8.583, 'vote_count': 3507}, {'adult': False, 'backdrop_path': '/zMwhWailP1WY7sb6AoE6b8ugoy.jpg', 'genre_ids': [16, 10751, 12, 14], 'id': 1007757, 'title': 'Swapped', 'original_language': 'en', 'original_title': 'Swapped', 'overview': 'A small woodland creature and a majestic bird, two natural sworn enemies of the Valley, magically trade places and set off on an adventure of a lifetime to switch back. Their journey soon uncovers a greater threat—one that could endanger not only their species, but the entire valley they call home.', 'popularity': 396.2282, 'poster_path': '/tHhxWxge06goXU6ZQH1hj7vK8Hd.jpg', 'release_date': '2026-05-01', 'softcore': False, 'video': False, 'vote_average': 8.995, 'vote_count': 1135}, {'adult': False, 'backdrop_path': '/9Z2uDYXqJrlmePznQQJhL6d92Rq.jpg', 'genre_ids': [10751, 35, 12, 14, 16], 'id': 1226863, 'title': 'The Super Mario Galaxy Movie', 'original_language': 'en', 'original_title': 'The Super Mario Galaxy Movie', 'overview': "Having thwarted Bowser's previous plot to marry Princess Peach, Mario and Luigi now face a fresh threat in Bowser Jr., who is determined to liberate his father from captivity and restore the family legacy. Alongside companions new and old, the brothers travel across the stars to stop the young heir's crusade.", 'popularity': 345.8493, 'poster_path': '/eJGWx219ZcEMVQJhAgMiqo8tYY.jpg', 'release_date': '2026-04-01', 'softcore': False, 'video': False, 'vote_average': 6.706, 'vote_count': 876}, {'adult': False, 'backdrop_path': '/gkh6Nt8DtY1XT4gQsyFq9XAVJlJ.jpg', 'genre_ids': [18, 35], 'id': 350, 'title': 'The Devil Wears Prada', 'original_language': 'en', 'original_title': 'The Devil Wears Prada', 'overview': 'A young woman from the Midwest gets more than she bargained for when she moves to New York to become a writer and ends up as the assistant to the tyrannical, larger-than-life editor-in-chief of a major fashion magazine.', 'popularity': 300.6443, 'poster_path': '/8912AsVuS7Sj915apArUFbv6F9L.jpg', 'release_date': '2006-06-29', 'softcore': False, 'video': False, 'vote_average': 7.4, 'vote_count': 13457}, {'adult': False, 'backdrop_path': '/p8777bPIlyFYcjqP2hU8htoz1RG.jpg', 'genre_ids': [28, 53], 'id': 1318447, 'title': 'Apex', 'original_language': 'en', 'original_title': 'Apex', 'overview': "A grieving woman pushing her limits on a solo adventure in the Australian wild is ensnared in a twisted game with a cunning killer who thinks she's prey.", 'popularity': 251.6251, 'poster_path': '/eTp7gSPkSF3Aw79mNx1NkBP1PZT.jpg', 'release_date': '2026-04-24', 'softcore': False, 'video': False, 'vote_average': 6.632, 'vote_count': 1068}, {'adult': False, 'backdrop_path': '/1x9e0qWonw634NhIsRdvnneeqvN.jpg', 'genre_ids': [10749, 18], 'id': 1523145, 'title': 'Your Heart Will Be Broken', 'original_language': 'ru', 'original_title': 'Твоё сердце будет разбито', 'overview': 'High school student Polina is saved from bullying at her new school and makes a deal with the main bully Bars: he must pretend to be her boyfriend and protect her, and she must do everything he says. During this game, the couple develops real feelings, but her family and classmates have reasons to separate the lovers.', 'popularity': 224.5883, 'poster_path': '/7wIBfBl2gejt6xHxNSK0reVIm7E.jpg', 'release_date': '2026-03-26', 'softcore': False, 'video': False, 'vote_average': 6.776, 'vote_count': 78}, {'adult': False, 'backdrop_path': '/xA6AM5MvEkieZKlv1Tn3sN23I7i.jpg', 'genre_ids': [28, 18, 10749], 'id': 1630423, 'title': 'My Dearest Assassin', 'original_language': 'th', 'original_title': 'เลือดรัก นักฆ่า', 'overview': 'Hunted for her rare blood type, a caged woman vows to fight alongside the assassin she loves to protect their future when an old enemy resurfaces.', 'popularity': 187.3038, 'poster_path': '/ul4dQcA68mtSx8J56N5gEcaCCtP.jpg', 'release_date': '2026-05-06', 'softcore': False, 'video': False, 'vote_average': 8.583, 'vote_count': 169}, {'adult': False, 'backdrop_path': '/jAJYVbVR5fP0BeTQXRP1BXjW5bl.jpg', 'genre_ids': [18], 'id': 1669050, 'title': 'Tayuan 2', 'original_language': 'tl', 'original_title': 'Tayuan 2', 'overview': 'A charming bus conductor drawn to both men and women who feels an unexpected spark with a shy commuter. On crowded bus rides where bodies brush, desire grows and love becomes messy.', 'popularity': 162.9065, 'poster_path': '/gkHNa8q3RNhgj2EMuoYWJUHsMa6.jpg', 'release_date': '2026-04-17', 'softcore': False, 'video': False, 'vote_average': 4.667, 'vote_count': 6}, {'adult': False, 'backdrop_path': '/4EAAwpylq313qrDqpCxulUrXBNF.jpg', 'genre_ids': [28, 14, 12], 'id': 931285, 'title': 'Mortal Kombat II', 'original_language': 'en', 'original_title': 'Mortal Kombat II', 'overview': 'The fan favorite champions—now joined by Johnny Cage himself—are pitted against one another in the ultimate, no-holds barred, gory battle to defeat the dark rule of Shao Kahn that threatens the very existence of the Earthrealm and its defenders.', 'popularity': 149.8611, 'poster_path': '/lIsMeDbwntNXSUVHmWMMRXEZOVc.jpg', 'release_date': '2026-05-06', 'softcore': False, 'video': False, 'vote_average': 6.997, 'vote_count': 199}, {'adult': False, 'backdrop_path': '/5AsIFZ2AJC7JcGpq40aRPuRuaRc.jpg', 'genre_ids': [18], 'id': 1241752, 'title': 'Rita', 'original_language': 'tl', 'original_title': 'Rita', 'overview': 'Rita, who finds herself alone when husband Ariel works abroad. They both find solace and sexual satisfaction in other people. When Ariel comes back, they both act like nothing happened. But will this keep their marriage from falling apart?', 'popularity': 170.7282, 'poster_path': '/pXENxAzOBrTSDJGxDcUnlNTNmWr.jpg', 'release_date': '2024-03-22', 'softcore': False, 'video': False, 'vote_average': 6.045, 'vote_count': 22}, {'adult': False, 'backdrop_path': '/9dMp9t0d0nIGhiil8TyqChwiNwA.jpg', 'genre_ids': [53, 27, 35], 'id': 1266127, 'title': 'Ready or Not: Here I Come', 'original_language': 'en', 'original_title': 'Ready or Not: Here I Come', 'overview': 'Moments after surviving an all-out attack from the Le Domas family, Grace discovers she’s reached the next level of the nightmarish game — and this time with her estranged sister Faith at her side. Grace has one chance to survive, keep her sister alive, and claim the High Seat of the Council that controls the world. Four rival families are hunting her for the throne, and whoever wins rules it all.', 'popularity': 158.0376, 'poster_path': '/13ZcJzSGEqVgDSqsS9U5EkQwPkV.jpg', 'release_date': '2026-03-19', 'softcore': False, 'video': False, 'vote_average': 7.611, 'vote_count': 733}, {'adult': False, 'backdrop_path': '/iN41Ccw4DctL8npfmYg1j5Tr1eb.jpg', 'genre_ids': [878, 12, 14], 'id': 83533, 'title': 'Avatar: Fire and Ash', 'original_language': 'en', 'original_title': 'Avatar: Fire and Ash', 'overview': "In the wake of the devastating war against the RDA and the loss of their eldest son, Jake Sully and Neytiri face a new threat on Pandora: the Ash People, a violent and power-hungry Na'vi tribe led by the ruthless Varang. Jake's family must fight for their survival and the future of Pandora in a conflict that pushes them to their emotional and physical limits.", 'popularity': 160.2008, 'poster_path': '/aabwWZWx6z1aYP4PX2ADvbDKktd.jpg', 'release_date': '2025-12-17', 'softcore': False, 'video': False, 'vote_average': 7.475, 'vote_count': 3068}, {'adult': False, 'backdrop_path': '/hlZGaey4lR9hc4rGxZRAmIEsZOc.jpg', 'genre_ids': [28, 18], 'id': 1292415, 'title': 'Beast', 'original_language': 'en', 'original_title': 'Beast', 'overview': 'MMA legend Patton James, now a commercial fisherman, is pulled back into the cage when his brother is in danger. Reuniting with his old coach Sammy, he commits to one final fight in one championship against the brutal champion Xavier Grau.', 'popularity': 156.5965, 'poster_path': '/7NrvUI3vnW8H3rD7ExKcTL7KRcQ.jpg', 'release_date': '2026-04-10', 'softcore': False, 'video': False, 'vote_average': 6.6, 'vote_count': 28}, {'adult': False, 'backdrop_path': '/6ELCZlTA5lGUops70hKdB83WJxH.jpg', 'genre_ids': [28, 14, 12], 'id': 460465, 'title': 'Mortal Kombat', 'original_language': 'en', 'original_title': 'Mortal Kombat', 'overview': "Washed-up MMA fighter Cole Young, unaware of his heritage, and hunted by Emperor Shang Tsung's best warrior, Sub-Zero, seeks out and trains with Earth's greatest champions as he prepares to stand against the enemies of Outworld in a high stakes battle for the universe.", 'popularity': 164.8496, 'poster_path': '/ybrX94xQm8lXYpZAPRmwD9iIbWP.jpg', 'release_date': '2021-04-07', 'softcore': False, 'video': False, 'vote_average': 7.024, 'vote_count': 6540}, {'adult': False, 'backdrop_path': '/u53UYu5XG2hNgWGvs3xGhAVzypl.jpg', 'genre_ids': [12, 16, 35, 10751, 878], 'id': 1327819, 'title': 'Hoppers', 'original_language': 'en', 'original_title': 'Hoppers', 'overview': "Scientists have discovered how to 'hop' human consciousness into lifelike robotic animals, allowing people to communicate with animals as animals. Animal lover Mabel seizes an opportunity to use the technology, uncovering mysteries within the animal world beyond anything she could have imagined.", 'popularity': 150.0152, 'poster_path': '/xjtWQ2CL1mpmMNwuU5HeS4Iuwuu.jpg', 'release_date': '2026-03-04', 'softcore': False, 'video': False, 'vote_average': 8.064, 'vote_count': 1103}, {'adult': False, 'backdrop_path': '/hdLsZ3dCjKt5A6xDpoo3UFgcTSm.jpg', 'genre_ids': [27, 28], 'id': 1426822, 'title': 'Mortal Game', 'original_language': 'en', 'original_title': 'Mortal Game', 'overview': 'A group of hunters travel to a mysterious island to track down a legendary forest creature. They soon realize their guide has set them up as bait, forcing them to confront a highly intelligent predator that terrorizes them one by one.', 'popularity': 159.6725, 'poster_path': '/iCvucorbs3hFqWshDbLe0fHzB71.jpg', 'release_date': '2025-02-03', 'softcore': False, 'video': False, 'vote_average': 5.6, 'vote_count': 5}, {'adult': False, 'backdrop_path': '/xBT0oNq6rsTFv4SxG5uGRIEOrq6.jpg', 'genre_ids': [10402, 18], 'id': 936075, 'title': 'Michael', 'original_language': 'en', 'original_title': 'Michael', 'overview': 'The story of Michael Jackson, one of the most influential artists the world has ever known, and his life beyond the music. His journey from the discovery of his extraordinary talent as the lead of the Jackson Five, to the visionary artist whose creative ambition fueled a relentless pursuit to become the biggest entertainer in the world, highlighting both his life off-stage and some of the most iconic performances from his early solo career.', 'popularity': 128.3006, 'poster_path': '/tBtqTCimYm3DKck3t8A2mgJaKVK.jpg', 'release_date': '2026-04-22', 'softcore': False, 'video': False, 'vote_average': 7.577, 'vote_count': 763}, {'adult': False, 'backdrop_path': '/rZfmzpixLKLR3Hg2u0WgC7XLFl8.jpg', 'genre_ids': [27], 'id': 1339713, 'title': 'Obsession', 'original_language': 'en', 'original_title': 'Obsession', 'overview': 'After breaking the mysterious "One Wish Willow" to win his crush\'s heart, a hopeless romantic finds himself getting exactly what he asked for but soon discovers that some desires come at a dark, sinister price.', 'popularity': 125.9389, 'poster_path': '/40I66L7QKguTFDPvcLcdiTbAD7I.jpg', 'release_date': '2026-04-16', 'softcore': False, 'video': False, 'vote_average': 8.096, 'vote_count': 89}, {'adult': False, 'backdrop_path': '/bVGHSe47W6oCQL1Q88pvRAet51A.jpg', 'genre_ids': [18, 9648], 'id': 1330021, 'title': 'Remarkably Bright Creatures', 'original_language': 'en', 'original_title': 'Remarkably Bright Creatures', 'overview': 'Through unlikely bonds formed during night shifts at a local aquarium, Tova, an elderly widow, learns of a life-changing discovery that may bring her joy and wonder once again.', 'popularity': 126.7479, 'poster_path': '/9HcEqn3D4J6b2Z0jK54id9nA0fr.jpg', 'release_date': '2026-05-07', 'softcore': False, 'video': False, 'vote_average': 8.534, 'vote_count': 295}], 'total_pages': 56883, 'total_results': 1137645}

In [29]:
data.keys()

dict_keys(['page', 'results', 'total_pages', 'total_results'])

In [30]:
data["page"]

1

In [39]:
data["results"][1]

{'adult': False,
 'backdrop_path': '/2I1OFQJ0L9T0dpU6FobKFWV2PxX.jpg',
 'genre_ids': [878, 12],
 'id': 687163,
 'title': 'Project Hail Mary',
 'original_language': 'en',
 'original_title': 'Project Hail Mary',
 'overview': 'Science teacher Ryland Grace wakes up on a spaceship light years from home with no recollection of who he is or how he got there. As his memory returns, he begins to uncover his mission: solve the riddle of the mysterious substance causing the sun to die out. He must call on his scientific knowledge and unorthodox ideas to save everything on Earth from extinction.',
 'popularity': 479.091,
 'poster_path': '/yihdXomYb5kTeSivtFndMy5iDmf.jpg',
 'release_date': '2026-03-15',
 'softcore': False,
 'video': False,
 'vote_average': 8.583,
 'vote_count': 3507}

In [32]:
data["total_pages"]

56883

In [33]:
data["total_results"]

1137645